### ISSUE TITLE
Are you?

### ISSUE THREAD

**Issue by Brandon324** [M3chanik/Idle-Python-Champions#1]
Are you still working on this? Can you please transfer ownership to me if you're not going to continue this, please? 

Thank you!

**Comment by M3chanik** [comment]
Probably not, it was just an idle (hah) curiosity if it could be done while I was still playing the game.  You're welcome to fork it and add more features, I'm not playing anymore

**Comment by Brandon324** [comment]
Okay, can you transfer ownership if you're not going to play anymore?

**Comment by M3chanik** [comment]
Sorry, I'd prefer to leave it here as sort of a resume thing.

**Comment by Brandon324** [comment]
Okay
